export const __GADGETS360_CARTITEMS = "__GADGETS360_CARTITEMS";
export const __GADGETS360_USERINFO = "__GADGETS360_USERINFO";
export const __GADGETS360_SHIPPING_ADDRESS = "__GADGETS360_SHIPPING_ADDRESS";
export const __GADGETS360_PAYMENT_METHOD = "__GADGETS360_PAYMENT_METHOD";
